# Site settings
title: Walter Bolitto Carvalho
description: |
  Educador, pesquisador e desenvolvedor de jogos

url: https://bolitto.github.io/

about_title: Sobre
publicacoes_title: Publicações
projects_title: Projetos

# User settings
user_description_appendix: |

## Tracker
google_analytics_id: UA-133311202-1

email: bolitto.walter@gmail.com
#angellist: rassaby

relevant_tags: ['textos', 'eventos', 'produção-técnica']

resume_url:

author: Walter Bolitto Carvalho
author_title: 
author_photo: perfil.png
user_description_short: |
  Educador popular, mestrado em Ciência da Computação (UFABC), pós-graduação em Educação e Tecnologia (UFSCar). Pesquisa e prática em uma articulação entre jogos educacionais, tecnologias assistivas e teorias de currículo.
  Desenvolvedor de jogos e tecnologias educacionais para ensino de ciências na educação formal e não-formal.
keywords: 'bolitto,walter bolitto,walter bolitto carvalho,educação,board games,jogos,educação e tecnologia'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/sobre'
publicacoes_url: '/publicacoes'

plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
